#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source secure enviroment settings
if [[ -s "$HOME/.secure/init.zsh" ]]; then
  source "$HOME/.secure/init.zsh"
fi

# Java
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre

# Android SDK
export ANDROID_HOME=$HOME/.linuxbrew/opt/android-sdk
export ANDROID_SDK=$HOME/.linuxbrew/opt/android-sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Linuxbrew
if [[ -d /home/linuxbrew/.linuxbrew/bin ]]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"
else
  export PATH=$PATH:$HOME/.linuxbrew/bin
fi

# Yarn
export PATH=$PATH:$HOME/.config/yarn/global/node_modules/.bin

# Go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
