#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Source secure enviroment settings
if [[ -s "$HOME/.secure/init.zsh" ]]; then
  source "$HOME/.secure/init.zsh"
fi

# Android SDK
export PATH=$PATH:/opt/android-sdk-linux/tools
export PATH=$PATH:/opt/android-sdk-linux/platform-tools

# Linuxbrew
export PATH=$PATH:$HOME/.linuxbrew/bin

# Go
export GOPATH=$HOME/work/go
export PATH=$PATH:$GOPATH/bin
if [[ -d $GOPATH ]]; then
  mkdir -p $GOPATH
fi

# Yarn
export PATH=$PATH:$HOME/.config/yarn/global/node_modules/.bin
