#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Android SDK
export PATH=$PATH:/opt/android-sdk-linux/tools
export PATH=$PATH:/opt/android-sdk-linux/platform-tools

# Linuxbrew
export PATH=$PATH:$HOME/.linuxbrew/bin
export HOMEBREW_GITHUB_API_TOKEN="57da9552dfad4309dcfb9191b681056c489163dc"
