#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Add git-flow completition
source /home/pedroxs/.zprezto/modules/git/git-flow-completition/git-flow-completion.zsh
#fpath=("/home/pedroxs/.zprezto/modules/completion/external/src/" $fpath)

# tips from http://joshsymonds.com/blog/2014/06/12/shell-awesomeness-with-prezto/
# only fools wouldn't do this ;-)
export EDITOR="subl -n -w"

# Case insensitive globbing
setopt NO_CASE_GLOB
setopt EXTENDED_GLOB

# json pretty print
alias json='python -mjson.tool'

# AWS cli completition
export PATH=/usr/local/aws/bin:$PATH
source /usr/local/bin/aws_zsh_completer.sh

export NVM_DIR="/home/pedroxs/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
