#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Use the builtin which command
unalias which

# Add git-flow completition
source "${ZDOTDIR:-$HOME}/.zprezto/modules/git/external/git-flow-completion.zsh"

# tips from http://joshsymonds.com/blog/2014/06/12/shell-awesomeness-with-prezto/
# only fools wouldn't do this ;-)
#export EDITOR="subl -n -w"

# Case insensitive globbing
setopt NO_CASE_GLOB
setopt EXTENDED_GLOB

# json pretty print
alias json='python -mjson.tool'

# AWS cli completition
if [[ -d /usr/local/aws/bin ]]; then
  export PATH=/usr/local/aws/bin:$PATH
  source /usr/local/bin/aws_zsh_completer.sh
fi

# zsh nvm plugin
if [[ -d "$HOME/.zsh-nvm" ]]; then
  export NVM_LAZY_LOAD=true
  source "$HOME/.zsh-nvm/zsh-nvm.plugin.zsh"
else
  # npm config if no nvm detected
  export NPM_CONFIG_PREFIX="$HOME/.npm-global"
  if [[ ! -d "$NPM_CONFIG_PREFIX" ]]; then
    mkdir -p "$NPM_CONFIG_PREFIX"
  fi
fi

# linux brew completition
if [[ -d "$HOME/.linuxbrew" ]]; then
  fpath=($HOME/.linuxbrew/completions/zsh $fpath)
  fpath=($HOME/.linuxbrew/share/zsh-completions $fpath)
fi

###-tns-completion-start-###
if [ -f $HOME/.tnsrc ]; then 
    source $HOME/.tnsrc 
fi
###-tns-completion-end-###

# vim settings
if [ -e /usr/bin/vimx ]; then 
  alias vim='/usr/bin/vimx'; 
fi

